root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 10
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: pentagon.so
    config:
      polygon_api_key: <polygon_api_key>
      tiingo_api_key: <tiingo_api_key>
      twelve_api_keys:
        - <twelve_api_key>
        - <twelve_api_key2>
        - <twelve_api_key3>
        - <twelve_api_key4>
        - <twelve_api_key5>
        - <twelve_api_key6>
        - <twelve_api_key7>
        - <twelve_api_key8>
        - <twelve_api_key9>
        - <twelve_api_key10>
        - <twelve_api_key11>
        - <twelve_api_key12>
        - <twelve_api_key13>
      query_start: 2017-01-01 00:00
      timeframes:
        - 12Min
        - 15Min
        - 20Min
        - 30Min
        - 1H
        - 2H
      crypto_symbols:
        - BTCUSD
        - BNBUSD
        - DASHUSD
        - ETHUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XMRUSD
        - XRPUSD
      forex_symbols:
        - EURUSD
        - GBPUSD
        - USDJPY 
        - AUDUSD
        - USDCAD
        - USDCHF
        - USDMXN 
        - USDBRL
        - USDDKK 
        - USDNOK 
        - USDSEK
        - USDCNH 
        - USDHKD
        - USDRUB
        - KRWUSD
        - TWDUSD
        - USDSGD
        - USDINR 
        - THBUSD
        - VNDUSD
        - PHPUSD
        - AUDUSD
        - NZDUSD
        - ZARUSD
        - XAGUSD
        - XAUUSD
        - XPDUSD
        - XPTUSD
        - XBRUSD
      equity_symbols:
        - DIA
        - SPY
        - QQQ
        - IWM
        - XLY
        - XLF
        - XLK
        - XLRE
        - XLE
        - XLC
        - XLU
        - XLV
        - XLP
        - XLB
        - IGSB
        - VCSH
        - IGIB
        - VCIT
        - VCLT
        - IGLB
        - SHY
        - VGSH
        - SCHO
        - VTIP
        - IEF
        - VGIT
        - SCHR
        - IEI
        - VGLT
        - TLT
        - GOVT
        - TIP
        - SCHP
        - VXX
        - VXZ